FROM --platform=linux/amd64 python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy
COPY ./backend.py /code/
COPY ./frontend.py /code/
COPY ./constants.py /code/
COPY ./utils.py /code/
COPY ./.env /code/
COPY ./models.py /code/

# Expose port
EXPOSE 7860

CMD ["python", "frontend.py"]
