FROM --platform=linux/amd64 python:3.10

WORKDIR /code

RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir fastapi uvicorn pydantic ollama requests python-multipart \
  azure.storage.blob azure-cosmos chromadb langchain pypdf sentence_transformers

# 
COPY ./backend.py /code/
COPY ./constants.py /code/
COPY ./utils.py /code/
COPY ./.env /code/
COPY ./models.py /code/

# Expose
EXPOSE 8000

# 
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]