# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    app: {{ include "weaviate.name" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "weaviate.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "weaviate.name" . }}
    spec:
      containers:
      - name: weaviate
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        command: {{ toYaml .Values.deployment.command | nindent 8 }}
        ports:
        - containerPort: 8080
        - containerPort: 50051
        resources:
          requests:
            memory: {{ .Values.deployment.resources.requests.memory }}
            cpu: {{ .Values.deployment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.deployment.resources.limits.memory }}
            cpu: {{ .Values.deployment.resources.limits.cpu }}
        env:
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: 'true'
        - name: DEFAULT_VECTORIZER_MODULE 
          value: 'text2vec-ollama'
        - name: ENABLE_MODULES
          value: 'text2vec-ollama'
        - name: ENABLE_API_BASED_MODULES
          value: 'true'
        - name: CLUSTER_HOSTNAME
          value: 'node1'
        - name: AUTOSCHEMA_ENABLED
          value: 'false'
        - name: QUERY_MAXIMUM_RESULTS
          value: "50000"
        - name: RAFT_BOOTSTRAP_EXPECT
          value: '1'
        - name: RAFT_JOIN
          value: 'node1:8300'
        volumeMounts:
        - name: weaviate-data
          mountPath: /var/lib/weaviate
      volumes:
      - name: weaviate-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      imagePullSecrets:
      {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}

