# Service Configuration
service:
  enabled: true
  name: weaviate
  namespace: default
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051
  selector:
    app: weaviate

# Persistent Volume Claim Configuration
pvc:
  enabled: true
  name: weaviate-pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-storage

storageClass:
  name: fast-storage  # Name of the StorageClass
  provisioner: disk.csi.azure.com  # Use the appropriate provisioner for your cloud provider
  volumeBindingMode: Immediate  # Set this to Immediate for immediate volume binding
  reclaimPolicy: Retain  # Optional: Retain the volume after PVC deletion

pv:
  name: weaviate-pv  # Name of the PersistentVolume
  size: 10Gi  # Storage size of the volume
  accessMode: ReadWriteOnce  # Access mode for the volume
  reclaimPolicy: Retain  # Reclaim policy for the volume (Retain/Delete)
  storageClassName: managed  # Storage class name
  hostPath:  # This will store data on the node’s filesystem, useful for testing/development
    path: "/var/lib/weaviate"  # Define the path on the node where the data will be stored
    type: DirectoryOrCreate  # Create the directory if it doesn't exist

# Deployment Configuration
deployment:
  replicas: 1
  name: weaviate
  labels:
    app: weaviate
  image:
    repository: pocgenaidade.azurecr.io/containergroup
    tag: weaviate-container
  imagePullPolicy: Always
  command:
    - "weaviate"
    - "--host"
    - "0.0.0.0"
    - "--port"
    - "8080"
    - "--scheme"
    - "http"
  ports:
    - containerPort: 8080
    - containerPort: 50051
  volumes:
    - name: weaviate-data
      persistentVolumeClaim:
        claimName: weaviate-pvc
  volumeMounts:
    - name: weaviate-data
      mountPath: /var/lib/weaviate
  resources:
    requests:
      memory: "4Gi"
      cpu: "1"
    limits:
      memory: "16Gi"
      cpu: "4"
  env:
    - name: PERSISTENCE_DATA_PATH
      value: "/var/lib/weaviate"
    - name: QUERY_DEFAULTS_LIMIT
      value: "25"
    - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
      value: "true"
    - name: DEFAULT_VECTORIZER_MODULE 
      value: 'text2vec-ollama'
    - name: ENABLE_MODULES
      value: 'text2vec-ollama'
    - name: ENABLE_API_BASED_MODULES
      value: 'true'
    - name: CLUSTER_HOSTNAME
      value: 'node1'
    - name: AUTOSCHEMA_ENABLED
      value: 'false'
    - name: QUERY_MAXIMUM_RESULTS
      value: "50000"
    - name: RAFT_BOOTSTRAP_EXPECT
      value: '1'
    - name: RAFT_JOIN
      value: 'node1:8300'
  imagePullSecrets:
    - name: my-registry-key
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: type
                operator: In
                values:
                  - frontend-backend
